# Generated by Django 5.2.1 on 2025-05-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0002_alter_user_is_active_useractivatetoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivatetoken',
            old_name='expired',
            new_name='expired_at',
        ),
    ]
