# Generated by Django 5.2.1 on 2025-06-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0005_alter_user_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
