# Generated by Django 5.2.1 on 2025-06-26 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0006_remove_user_image_url_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tomorrow_goal', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diaries',
            },
        ),
        migrations.CreateModel(
            name='DiarySuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success', models.CharField(max_length=50)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary_app.diary')),
            ],
            options={
                'db_table': 'diary_successes',
            },
        ),
        migrations.CreateModel(
            name='MonthReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_number', models.IntegerField()),
                ('month_number', models.IntegerField()),
                ('common_ground', models.CharField(max_length=50)),
                ('my_values', models.CharField(max_length=50)),
                ('awareness', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'month_reflections',
            },
        ),
        migrations.CreateModel(
            name='WeekReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.IntegerField()),
                ('highlight', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('next_plan', models.CharField(max_length=50)),
                ('month_reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_reflections', to='diary_app.monthreflection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'week_reflections',
            },
        ),
        migrations.AddField(
            model_name='diary',
            name='week_reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_reflections', to='diary_app.weekreflection'),
        ),
        migrations.DeleteModel(
            name='UserActivateToken',
        ),
    ]
