# Generated by Django 5.2.1 on 2025-06-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0008_remove_diary_week_reflection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='tomorrow_goal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
