# Generated by Django 5.2.1 on 2025-07-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0009_alter_diary_tomorrow_goal'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
