# Generated by Django 5.2.1 on 2025-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0010_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
