# Generated by Django 5.2.1 on 2025-07-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0012_diary_week_reflection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthreflection',
            name='awareness',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthreflection',
            name='common_ground',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthreflection',
            name='my_values',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weekreflection',
            name='highlight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weekreflection',
            name='next_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weekreflection',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
