# Generated by Django 5.1.7 on 2025-08-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0014_alter_diary_created_at_alter_diarysuccess_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarysuccess',
            name='success',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monthreflection',
            name='awareness',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='monthreflection',
            name='common_ground',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='monthreflection',
            name='my_values',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weekreflection',
            name='highlight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weekreflection',
            name='next_plan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weekreflection',
            name='reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
