# Generated by Django 5.1.7 on 2025-08-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0015_alter_diarysuccess_success_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='tomorrow_goal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
